apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rgfu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rgfu
    app.kubernetes.io/part-of: tkrw-pr714-0075-0074-app
  name: devfile-sample-rgfu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rgfu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rgfu
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0074-tenant/tkrw-pr714-0075-0074-app/devfile-sample-rgfu@sha256:5de69057c13b065843e842409866b703ef7175a6cd6149ae147f4de522bf76e4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
